name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/php-dev:latest ./
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/php-dev:latest
